apiVersion: v2
name: test-1
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    version: "2.2.4"
