.generate-ci:
  image: alpine
  variables:
    # renovate: datasource=github-tags depName=carvel-dev/ytt
    YTT_VERSION: 0.45.3
    # renovate: datasource=github-tags depName=mikefarah/yq
    YQ_VERSION: 4.34.2
    # renovate: datasource=github-tags depName=stedolan/jq
    JQ_VERSION: jq-1.6

version: 37.11.1 # renovate: depName=renovate registryUrl=https://docs.renovatebot.com/helm-charts datasource=helm

# renovate: datasource=github-tags depName=nodejs/node versioning=node
ENV NODE_VERSION=10.19.0
