.generate-ci:
  image: alpine
  variables:
    YTT_VERSION: 0.46.0 # renovate: datasource=github-tags depName=carvel-dev/ytt
    YQ_VERSION: 4.35.2 # renovate: datasource=github-tags depName=mikefarah/yq
    JQ_VERSION: jq-1.7 # renovate: datasource=github-tags depName=stedolan/jq

      image: "ubuntu:16.10" # renovate: datasource=docker versioning=docker
      image: bitnami/kubectl:1.28 # renovate: datasource=docker versioning=docker
      image: quay.io/galexrt/node-exporter-textfiles:v20220901-124456-405 # renovate: datasource=docker versioning=docker
      image: machine424/preemption-events:0.1.0 # renovate: datasource=docker versioning=docker
      image: docker.io/library/alpine:3.18.4 # renovate: datasource=docker versioning=docker
      image: gcr.io/google_containers/pause-amd64:3.2 # renovate: datasource=docker versioning=docker
      image: velero/velero-plugin-for-aws:v1.8.0 # renovate: datasource=docker versioning=docker
